server {
    listen 8088;
    # Responde às duas URLs
    server_name conferencianacional-hml.trabalho.gov.br conferencianacional.trabalho.gov.br;

    root /usr/share/nginx/html;
    index index.html;

    # Cache forte para assets com hash
    location ~* \.(?:css|js|mjs|png|jpg|jpeg|gif|svg|webp|ico|ttf|otf|woff|woff2)$ {
        add_header Cache-Control "public, max-age=31536000, immutable";
        try_files $uri =404;

        # (Opcional) CORS apenas para os domínios autorizados — útil p/ fontes/JS
        if ($http_origin ~* ^https?://(conferencianacional-hml\.trabalho\.gov\.br|conferencianacional\.trabalho\.gov\.br)$) {
            add_header Access-Control-Allow-Origin $http_origin always;
            add_header Vary Origin always;
        }
    }

    # SPA fallback
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Não cachear HTML principal
    location = /index.html {
        add_header Cache-Control "no-cache, no-store, must-revalidate";
    }

    # Gzip básico
    gzip on;
    gzip_types text/plain text/css application/javascript application/json image/svg+xml;
    gzip_min_length 1024;

    # (Opcional) cabeçalhos de segurança mínimos
    add_header X-Content-Type-Options nosniff always;
    add_header X-Frame-Options SAMEORIGIN always;
    add_header Referrer-Policy no-referrer-when-downgrade always;
}
