version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sistema-votacao-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - sistema-votacao
    depends_on:
      - sqlserver

  nginx:
    image: nginx:alpine
    container_name: sistema-votacao-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx:/etc/nginx/conf.d
    networks:
      - sistema-votacao
    depends_on:
      - app

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sistema-votacao-sqlserver
    restart: unless-stopped
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "SistemaVotacao@2024"
      MSSQL_PID: "Express"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver-data:/var/opt/mssql
    networks:
      - sistema-votacao

networks:
  sistema-votacao:
    driver: bridge

volumes:
  sqlserver-data:
    driver: local
