services:
  websrt:
    container_name: websrt
    build:
      context: ./codigo-fonte/cliente
      dockerfile: Dockerfile.dev
    expose:
      - "3000"
    ports:
      - "8088:3000"
    volumes:
      - ./codigo-fonte/cliente:/app
      - /app/node_modules
    networks:
      - srt-network
    restart: unless-stopped
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true

  phpsrt:
    container_name: phpsrt
    build:
      context: ./codigo-fonte/servico
      dockerfile: Dockerfile
    ports:
      - "8090:80"
    expose:
      - "9000"
    volumes:
      - ./codigo-fonte/servico:/var/www/html
      - vendor-data:/var/www/html/vendor
      - storage-data:/var/www/html/storage
    networks:
      - srt-network
    restart: unless-stopped

networks:
  srt-network:
    driver: bridge

volumes:
  vendor-data:
    driver: local
  storage-data:
    driver: local
